"""item.source_updated_at to non_nullable, add feed.params field

Revision ID: 4b967d7d94c6
Revises: cf01415369d8
Create Date: 2026-04-18 12:14:31.002362

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b967d7d94c6'
down_revision: Union[str, Sequence[str], None] = 'cf01415369d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('params', sa.JSON(), nullable=True))

    # Backfill source_updated_at with source_published_at where null
    op.execute("UPDATE item SET source_updated_at = source_published_at WHERE source_updated_at IS NULL")

    # SQLite-safe alter
    with op.batch_alter_table('item') as batch_op:
        batch_op.alter_column(
            'source_updated_at',
            existing_type=sa.DATETIME(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('item') as batch_op:
        batch_op.alter_column(
            'source_updated_at',
            existing_type=sa.DATETIME(),
            nullable=True
        )
    op.drop_column('feed', 'params')
    # ### end Alembic commands ###
