"""Add item.meta field

Revision ID: 675fe190439f
Revises: 4b967d7d94c6
Create Date: 2026-04-18 18:42:44.094847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '675fe190439f'
down_revision: Union[str, Sequence[str], None] = '4b967d7d94c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'meta')
    # ### end Alembic commands ###
