"""Move target_type from ScrapeJob to ScrapeJobRecord

Revision ID: ca917ef1b2bc
Revises: a9082847a37a
Create Date: 2026-04-26 11:05:01.438309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ca917ef1b2bc'
down_revision: Union[str, Sequence[str], None] = 'a9082847a37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapejobrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.Enum('SOURCE', 'FEED', 'ITEM', name='scrapetargettype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapejobrecord', schema=None) as batch_op:
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
