"""Add item.thumbnail_url field

Revision ID: df68e3cd2b71
Revises: c33971395131
Create Date: 2026-04-21 23:42:32.116573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'df68e3cd2b71'
down_revision: Union[str, Sequence[str], None] = 'c33971395131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'thumbnail_url')
    # ### end Alembic commands ###
